### ISSUE TITLE
marquerPremierPoint()

### ISSUE THREAD

**Issue by esdras-assikid** [esdras-assikid/ia-XAEX12#2]
Cette méthode doit permettre de marquer le premier point le plus rapidement possible : 
- Saisir le palet en face
- Se décaler tout en avançant pour éviter ne pas être sur la trajectoire des autres palets
- Se remettre en direction de la ligne adverse
- Avancer jusqu'à détecter la ligne blanche, puis déposer le palet

**Comment by pilopa84** [comment]
J'ai 2 problèmes -> Comment faire pour faire avancer le robot d'une longueur fixe (genre 20cm) ?
                           -> J'ai une erreur sur     cs = new ColorSensor();  ça me renvoie Unhandled exception type FileNotFound exception 
                                qu'est ce que ca veut dire ?

**Comment by Marouan-git** [comment]
Dsl je n'avais pas vu ton commentaire, pour faire avancer le robot d'une distance donnée tu peux utiliser la méthode 
void travel (double distance). Tu peux voir ça dans la documentation de la classe MovePilot.
