### ISSUE TITLE
seRepositionner()

### ISSUE THREAD

**Issue by Marouan-git** [esdras-assikid/ia-XAEX12#4]
Cette méthode de la classe agent doit permettre au robot de se repositionner dans différents cas : 
- s'il se retrouve face à un mur
- s'il se retrouve face au robot adverse
- après avoir marqué un point
- si lorsqu'il se dirige vers l'endroit où se trouve le palet et le capteur de toucher n'a rien détecté (reculer et entamer une nouvelle recherche pour ajuster la direction ?)

D'autres cas à envisager ?.....

**Comment by ghost** [comment]
Je pense qu'on peut aussi considérer le cas où il se retrouve dans son propre camp
